ArtAuction.MVC/Models/ErrorViewModel.cs
namespace ArtAuction.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ArtAuction.MVC/Controllers/ArtworkController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using ArtAuction.Services.ArtworkServ;
using ArtAuction.Models.ArtworkVM;

namespace ArtAuction.Controllers;

public class ArtworkController : Controller {
    private readonly IArtworkService _service;

    public ArtworkController(IArtworkService service) {
        _service = service;
    }

    [Authorize]
    public async Task<IActionResult> Index() {
        return View(await _service.GetAllArtworkRelatedToUserAsync());
    }

    public async Task<IActionResult> All() {
        return View(await _service.GetAllArtworkAsync());
    }

    public async Task<IActionResult> Detail(int id) {
        return View(await _service.GetArtworkByIdAsync(id));
    }

    [Authorize]
    public async Task<IActionResult> Create() {
        ViewData["Genres"] = await _service.GetFullGenreSelectionAsync();
        return View();
    }

    [Authorize]
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ArtworkCreate model) {
        switch (await _service.CreateArtworkAsync(model)) {
            case null:
                TempData["ErrorMsg"] = "object failed to create"; return View(model);
            case false:
                TempData["ErrorMsg"] = "not all genres were added"; return View(model);
        }

        return RedirectToAction(nameof(Index));
    }
}

ArtAuction.MVC/Controllers/BidController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using ArtAuction.Models.BidVM;
using ArtAuction.Services.BidServ;

namespace ArtAuction.Controllers;

[Authorize] // dono how this is gonna work, uncomment later
public class BidController : Controller {
    private readonly IBidService _service;

    public BidController(IBidService service) {
        _service = service;
    }

    public async Task<IActionResult> Index(int id) {
        return View(await _service.GetAllBidsForArtworkAsync(id));
    }

    public IActionResult Create() {
        return View();
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(int id, BidCreate model) {
        if (!ModelState.IsValid) {
            TempData["ErrorMsg"] = "cannot set bid on artwork";
            return View(model);
        }
        if (!await _service.CreateBidAsync(id, model)) {
            TempData["ErrorMsg"] = "cannot set bid on artwork";
            return View(model);
        }
        return RedirectToAction("All", "Artwork");
    }
}

ArtAuction.MVC/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;

using ArtAuction.Services.GenreServ;
using ArtAuction.Models.GenreVM;
using Microsoft.AspNetCore.Authorization;

namespace ArtAuction.Controllers;

[Authorize]
public class GenreController : Controller {
    private readonly IGenreService _service;

    public GenreController(IGenreService service) {
        _service = service;
    }

    public async Task<IActionResult> Index(int id) {
        ViewData["Genres"] = await _service.GetAllGenresAsync();
        return View(await _service.GetArtworksFromGenresAsync(id));
    }

    public IActionResult Create() {
        return View();
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(GenreCreate model) {
        if (!ModelState.IsValid) {
            TempData["ErrorMsg"] = "Failed to create Genre";
            return View(model);
        }
        if (!await _service.CreateGenreAsync(model)) {
            TempData["ErrorMsg"] = "Failed to create Genre";
            return View(model);
        }
        return RedirectToAction(nameof(Index));
    }
}

ArtAuction.MVC/Controllers/HomeController.cs
using ArtAuction.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ArtAuction.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ArtAuction.MVC/Controllers/UserReviewController.cs
using Microsoft.AspNetCore.Mvc;

using ArtAuction.Services.UserReviewServ;
using ArtAuction.Models.UserReviewVM;
using Microsoft.AspNetCore.Authorization;

namespace ArtAuction.Controllers;

[Authorize]
public class UserReviewController : Controller {
    private readonly IUserReviewService _service;

    public UserReviewController(IUserReviewService service) {
        _service = service;
    }

    public async Task<IActionResult> Index(string id) {
        return View(await _service.GetAllUserReviewsOfAUser(id)); 
    }

    public IActionResult Create(string id) {
        return View();
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(string id, UserReviewCreate model) {// throws error after creation :(
        if (!await _service.CreateUserReviewAsync(id, model)) {
            TempData["ErrorMsg"] = "Failed to create Genre";
            return View(model);
        }
        return RedirectToAction("All", "Artwork");
    } 
}

ArtAuction.MVC/Views/Artwork/All.cshtml
@model List<ArtAuction.Models.ArtworkVM.ArtworkListItem>
@{
    ViewData["Title"] = "All artwork";
}

<div class="d-flex flex-wrap justify-content-between align-items-baseline">
    <h1>All Artworks</h1>
</div>

<table class="table table-striped border">
    <thead>
        <tr>
            <th>Finish date</th>
            <th>user</th>
            <th>art</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model is not null)
            @foreach (var art in Model) {
                <tr>
                    @*work on this crap*@
                    <td>@art.BiddingFinishDate</td>
                    <td>
                        <a class="nav-link text-decoration-none" asp-controller="UserReview" asp-action="Index" asp-route-id="@art.UserName" class="btn btn-sm btn-success">@art.UserName</a>
                    </td>
                    <td>
                        <a class="nav-link text-decoration-none" asp-action="Detail" asp-route-id="@art.Id">@art.Name</a>
                    </td>
                    <td>
                        <a asp-controller="Bid" asp-action="Create" asp-route-id="@art.Id" class="btn btn-sm btn-success">Place a Bid</a>
                        <a asp-controller="Bid" asp-action="Index" asp-route-id="@art.Id" class="btn btn-sm btn-success">View Bids</a>
                        <a asp-controller="UserReview" asp-action="Create" asp-route-id="@art.UserName" class="btn btn-sm btn-success">Review Artist</a>
                    </td>
                </tr>
            }
    </tbody>
</table> 

ArtAuction.MVC/Views/Artwork/Create.cshtml
@model ArtAuction.Models.ArtworkVM.ArtworkCreate
@{
    ViewData["Title"] = "Artwork creation";
    var genreList = ViewData["Genres"] as List<ArtAuction.Models.GenreVM.GenreListItem>;
    
}

@if (TempData["ErrorMsg"] != null) {
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error</strong> @TempData["ErrorMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<form asp-action="Create" method="post" class="row g-3">
    <div class="col-md-6">
        <label asp-for="@Model.Name" class="form-label"></label>
        <input asp-for="@Model.Name" class="form-control" />
    </div>
    <div class="col-md-6">
        <label asp-for="@Model.Description" class="form-label"></label>
        <input asp-for="@Model.Description" class="form-control" />
    </div>
    <div class="col-md-6">
        <label asp-for="@Model.CompletionDate" class="form-label"></label>
        <input asp-for="@Model.CompletionDate" type="date" class="form-control" />
    </div>
    @if (genreList is not null) {
        <div class="col-md-6">
            <label asp-for="@Model.GenreKeys" class="form-label"> select multiple genres with [ctrl]+[left click]</label>
            <select asp-for="@Model.GenreKeys" class="form-select" multiple="multiple">
                @foreach (var genre in genreList) {
                    <option value="@genre.Id"> @genre.Name </option>
                }
            </select>
        </div>
    }
    <div class="col d-flex justify-content-between align-items-baseline">
        <a asp-action="Index">Back to Artwork</a>
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

ArtAuction.MVC/Views/Artwork/Detail.cshtml
@model ArtAuction.Models.ArtworkVM.ArtworkDetail;
@{
    ViewData["Title"] = "Details";
}

<dl class="row">
    <dt>
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.DateCompleted)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.DateCompleted)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Genres)
    </dt>
    <dd>
        @foreach(var g in Model.Genres) {
            <p><a asp-controller="Genre" asp-action="Index" asp-route-id="@g.Id">@g.Name</a></p> @*need to link*@
        }
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.BiddingFinishDate)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.BiddingFinishDate)
    </dd>
</dl>

ArtAuction.MVC/Views/Artwork/Index.cshtml
@model List<ArtAuction.Models.ArtworkVM.ArtworkListItem>
@{
    string name = User.Identity?.Name ?? "error";
    ViewData["Title"] = $"{name} portfolio";
}

<div class="d-flex flex-wrap justify-content-between align-items-baseline">
    <h1>@name's Portfolio</h1>
    <a asp-controller="Artwork" asp-action="Create" class="btn btn-sm btn-success">Artwork creator</a>
</div>

<table class="table table-striped border">
    <thead>
        <tr>
            <th>Finish date</th>
            <th>user</th>
            <th>art</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model is not null)
            @foreach (var art in Model) {  
                <tr>
                    <td>@art.BiddingFinishDate</td>
                    <td>
                        <a class="nav-link text-decoration-none" asp-controller="UserReview" asp-action="Index" asp-route-id="@art.UserName">@art.UserName</a>
                    </td>
                    <td>
                        <a class="nav-link text-decoration-none" asp-action="Detail" asp-route-id="@art.Id">@art.Name</a>
                    </td>
                    <td>
                        @*
                        <a asp-controller="Bid" asp-action="Create" asp-route-id="@art.Id" class="btn btn-sm btn-success">Place a Bid</a>
                        <a asp-controller="UserReview" asp-action="Create" asp-route-id="@art.UserName" class="btn btn-sm btn-success">Review Artist</a>
                        *@
                        <a asp-controller="Bid" asp-action="Index" asp-route-id="@art.Id" class="btn btn-sm btn-success">View Bids</a>
                    </td>
                    
                </tr>
                
            }
    </tbody>
</table>

ArtAuction.MVC/Views/Bid/Create.cshtml
@model ArtAuction.Models.BidVM.BidCreate
@{
    ViewData["Title"] = "Place Bid";
}

@if (TempData["ErrorMsg"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error</strong> @TempData["ErrorMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<form asp-action="Create" method="post" class="row g-3">
    <div class="col-md-6">
        <label asp-for="@Model.Payment" class="form-label"></label>
        <input type="number" asp-for="@Model.Payment" class="form-control" />
    </div>
    <div class="col-md-6">
        <label asp-for="@Model.Address" class="form-label"></label>
        <input asp-for="@Model.Address" class="form-control" />
    </div>
    <div class="col d-flex justify-content-between align-items-baseline">
        <a asp-controller="Artwork" asp-action="Index">Back to Artwork</a>
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

ArtAuction.MVC/Views/Bid/Index.cshtml
@model List<ArtAuction.Models.BidVM.BidListItem> 
@{
    ViewData["Title"] = "Artwork's bids";
}
<div class="d-flex flex-wrap justify-content-between align-items-baseline">
    <h1>All Bids</h1>
    <a asp-controller="Artwork" asp-action="Index" class="btn btn-sm btn-success">Back to Artwork</a>
    <a asp-controller="Bid" asp-action="Create" class="btn btn-sm btn-success">Place a Bid</a>
</div>

<table class="table table-striped border">
    <thead>
        <tr>
            <th>DatePlaced</th>
            <th>Name</th>
            <th>Payment</th>
        </tr>
    </thead>
    <tbody>
        @if (Model is not null)
            @foreach (var bid in Model) {
                <tr>
                    <td>@bid.DatePlaced</td>
                    <td>@bid.Name</td>
                    <td>@bid.Payment</td>
                </tr>
            }
    </tbody>
</table>

ArtAuction.MVC/Views/Genre/Create.cshtml
@model ArtAuction.Models.GenreVM.GenreCreate
@{
    ViewData["Title"] = "Genre creation";
}

@if (TempData["ErrorMsg"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error</strong> @TempData["ErrorMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<form asp-action="Create" method="post" class="row g-3">
    <div class="col-md-6">
        <label asp-for="@Model.Name" class="form-label"></label>
        <input asp-for="@Model.Name" class="form-control" />
    </div>
    <div class="col-md-6">
        <label asp-for="@Model.Description" class="form-label"></label>
        <input asp-for="@Model.Description" class="form-control" />
    </div>

    <div class="col d-flex justify-content-between align-items-baseline">
        <a asp-controller="Artwork" asp-action="Index">Back to Artwork</a>
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

ArtAuction.MVC/Views/Genre/Index.cshtml
@model List<ArtAuction.Models.ArtworkVM.ArtworkListItem>
@{
    ViewData["Title"] = "Genre's artworks";
    var genreList = ViewData["Genres"] as List<ArtAuction.Models.GenreVM.GenreListItem>;
}

<div class="d-flex flex-wrap justify-content-between align-items-baseline">
    <h1>Genre's Artworks</h1>
    <a class="btn btn-sm btn-success" asp-area="" asp-controller="Genre" asp-action="Create">Create Genre</a>

</div>

@if (genreList is not null) {
    <div>
        <select onchange="document.location.href=this.value">
            <option> -- change genre -- </option>
            @foreach (var genre in genreList)
            {
                <option value="@Url.Action("Index", new {id = genre.Id})"> @genre.Name </option>
            }
        </select>
    </div>
}

<table class="table table-striped border">
    <thead>
        <tr>
            <th>Finish date</th>
            <th>user</th>
            <th>art</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model is not null)
            @foreach (var art in Model) {
                <tr>
                    <td>@art.BiddingFinishDate</td>
                    <td>
                        <a class="nav-link text-decoration-none" asp-controller="UserReview" asp-action="Index" asp-route-id="@art.UserName" class="btn btn-sm btn-success">@art.UserName</a>
                    </td>
                    <td>
                        <a class="nav-link text-decoration-none" asp-controller="Artwork" asp-action="Detail" asp-route-id="@art.Id">@art.Name</a>
                    </td>
                    <td>
                        <a asp-controller="Bid" asp-action="Create" asp-route-id="@art.Id" class="btn btn-sm btn-success">Place a Bid</a>
                        <a asp-controller="Bid" asp-action="Index" asp-route-id="@art.Id" class="btn btn-sm btn-success">View Bids</a>
                        <a asp-controller="UserReview" asp-action="Create" asp-route-id="@art.UserName" class="btn btn-sm btn-success">Review Artist</a>
                    </td>

                </tr>
            }
    </tbody>
</table>

ArtAuction.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ArtAuction.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AcuteArtAuction</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ArtAuction.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AcuteArtAuction</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artwork" asp-action="All">All Art</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artwork" asp-action="Index">My Portfolio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Index">Genre Art</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AcuteArtAuction - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ArtAuction.MVC/Views/UserReview/Create.cshtml
@model ArtAuction.Models.UserReviewVM.UserReviewCreate
@{
    ViewData["Title"] = "Post User Review";
}

@if (TempData["ErrorMsg"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error</strong> @TempData["ErrorMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<form asp-action="Create" method="post" class="row g-3">
    <div class="col-md-6">
        <label asp-for="@Model.Title" class="form-label"></label>
        <input asp-for="@Model.Title" class="form-control" />
    </div>
    <div class="col-md-6">
        <label asp-for="@Model.Contents" class="form-label"></label>
        <input asp-for="@Model.Contents" class="form-control" />
    </div>
    <div class="col-md-6">
        <label asp-for="@Model.Rating" class="form-label"></label>
        <input asp-for="@Model.Rating" class="form-control" />
    </div>
    <div class="col d-flex justify-content-between align-items-baseline">
        <a asp-controller="Artwork" asp-action="Index">Back to Artwork</a>
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

ArtAuction.MVC/Views/UserReview/Index.cshtml
@model List<ArtAuction.Models.UserReviewVM.UserReviewListItem>
@{
    string name = User.Identity?.Name ?? "error";
    ViewData["Title"] = $"reviews of {name}";
}

<div class="d-flex flex-wrap justify-content-between align-items-baseline">
    <h1>impressions of @name</h1>
    <a asp-controller="Artwork" asp-action="Index" class="btn btn-sm btn-success">Back to Artwork</a>
</div>

<table class="table table-striped border">
    <thead>
        <tr>
            <th>Title</th>
            <th>Contents</th>
            <th>Rating</th>
        </tr>
    </thead>
    <tbody>
        @if (Model is not null)
            @foreach (var review in Model) {
                <tr>
                    <td>@review.Title</td>
                    <td>@review.Contents</td>
                    <td>@review.Rating</td>
                </tr>
            }
    </tbody>
</table>